# Generated by Django 6.0 on 2026-01-05 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('contacto_nombre', models.CharField(blank=True, max_length=200)),
                ('contacto_puesto', models.CharField(blank=True, max_length=100)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20)),
                ('ruc_nit', models.CharField(blank=True, max_length=50, unique=True)),
                ('industria', models.CharField(blank=True, max_length=100)),
                ('empleados', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creado'],
            },
        ),
    ]
