# Generated by Django 5.2.6 on 2026-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado_salud',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('observacion', 'Observación'), ('alarma', 'Alarma'), ('falla', 'Falla'), ('sin_medicion', 'Sin Medición')], default='sin_medicion', help_text='Estado actual de salud del activo basado en mediciones', max_length=20),
        ),
    ]
