# Generated by Django 5.2.6 on 2026-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activo_estado_salud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='estado_salud',
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('observacion', 'Observación'), ('alarma', 'Alarma'), ('falla', 'Falla'), ('sin_medicion', 'Sin Medición')], default='sin_medicion', help_text='Estado actual del activo basado en mediciones', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('observacion', 'Observación'), ('alarma', 'Alarma'), ('falla', 'Falla'), ('sin_medicion', 'Sin Medición')], default='sin_medicion', help_text='Estado actual del equipo basado en mediciones', max_length=20),
        ),
    ]
