# Generated by Django 5.2.6 on 2026-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['-creado'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-creado'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='activo',
            name='foto_termica',
            field=models.ImageField(blank=True, help_text='Foto térmica del activo', null=True, upload_to='termografias/activos/'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin Observaciones', help_text='Potencia, RPM, Voltaje, Fases, etc. (máx 500 caracteres)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin Observaciones', help_text='Potencia, RPM, Voltaje, etc. (máx 500 caracteres)', max_length=500, null=True),
        ),
    ]
