# Generated by Django 5.2.6 on 2026-01-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_activo_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisTermico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_promedio', models.FloatField(default=0, help_text='Temperatura promedio estimada (0-100)')),
                ('porcentaje_zona_critica', models.FloatField(default=0, help_text='Porcentaje de píxeles en zona crítica')),
                ('porcentaje_zona_alerta', models.FloatField(default=0, help_text='Porcentaje de píxeles en zona de alerta')),
                ('temperatura_maxima', models.FloatField(default=0, help_text='Temperatura máxima detectada')),
                ('temperatura_minima', models.FloatField(default=0, help_text='Temperatura mínima detectada')),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='normal', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_termico', to='core.activo')),
            ],
            options={
                'verbose_name': 'Análisis Térmico',
                'verbose_name_plural': 'Análisis Térmicos',
            },
        ),
    ]
