# Generated by Django 5.2.6 on 2026-01-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_analisistermico'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisistermico',
            name='rango_maximo',
            field=models.FloatField(default=0, help_text='Rango máximo de temperatura en °C'),
        ),
        migrations.AddField(
            model_name='analisistermico',
            name='rango_minimo',
            field=models.FloatField(default=0, help_text='Rango mínimo de temperatura en °C'),
        ),
        migrations.AlterField(
            model_name='analisistermico',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('alarma', 'Alarma'), ('emergencia', 'Emergencia'), ('sin_medicion', 'Sin Medición')], default='sin_medicion', max_length=20),
        ),
    ]
