# Generated by Django 5.2.6 on 2026-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_analisistermico_rango_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('observacion', 'Observación'), ('alarma', 'Alarma'), ('emergencia', 'Emergencia'), ('falla', 'Falla'), ('sin_medicion', 'Sin Medición')], default='sin_medicion', help_text='Estado actual del activo basado en mediciones', max_length=20),
        ),
    ]
