# Generated by Django 5.2.6 on 2026-01-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_activo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisistermico',
            name='zona_alarma_max',
            field=models.FloatField(default=65, help_text='Temperatura máxima - Zona ALARMA'),
        ),
        migrations.AddField(
            model_name='analisistermico',
            name='zona_alarma_min',
            field=models.FloatField(default=50, help_text='Temperatura mínima - Zona ALARMA'),
        ),
        migrations.AddField(
            model_name='analisistermico',
            name='zona_bueno_max',
            field=models.FloatField(default=50, help_text='Temperatura máxima - Zona BUENO'),
        ),
        migrations.AddField(
            model_name='analisistermico',
            name='zona_bueno_min',
            field=models.FloatField(default=20, help_text='Temperatura mínima - Zona BUENO'),
        ),
        migrations.AddField(
            model_name='analisistermico',
            name='zona_emergencia_max',
            field=models.FloatField(default=100, help_text='Temperatura máxima - Zona EMERGENCIA'),
        ),
        migrations.AddField(
            model_name='analisistermico',
            name='zona_emergencia_min',
            field=models.FloatField(default=65, help_text='Temperatura mínima - Zona EMERGENCIA'),
        ),
    ]
