# Generated by Django 5.2.6 on 2026-01-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_analisistermico_zona_alarma_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisistermico',
            name='porcentaje_zona_caliente',
            field=models.FloatField(default=0, help_text='Porcentaje de píxeles en zona caliente'),
        ),
    ]
