# Generated by Django 5.2.6 on 2026-01-16 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_analisistermico_porcentaje_zona_caliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestreoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_muestreo', models.DateField(help_text='Fecha en que se realizó el muestreo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreos', to='core.activo')),
            ],
            options={
                'verbose_name': 'Muestreo de Activo',
                'verbose_name_plural': 'Muestreos de Activos',
                'ordering': ['-fecha_muestreo'],
                'unique_together': {('activo', 'fecha_muestreo')},
            },
        ),
    ]
