# Generated by Django 5.2.6 on 2026-01-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_muestreoactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisistermico',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_termicos', to='core.activo'),
        ),
    ]
