# Generated by Django 5.2.6 on 2026-01-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_analisistermico_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='plano_planta',
            field=models.ImageField(blank=True, null=True, upload_to='plantas/', verbose_name='Plano de la planta'),
        ),
    ]
