# Generated by Django 5.2.6 on 2026-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sucursal_plano_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/', verbose_name='Logo o icono del cliente'),
        ),
    ]
