# Generated by Django 5.2.6 on 2026-01-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cliente_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuestreoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_muestreo', models.DateField(help_text='Fecha en que se realizó el muestreo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreos', to='core.equipo')),
            ],
            options={
                'verbose_name': 'Muestreo de Equipo',
                'verbose_name_plural': 'Muestreos de Equipos',
                'ordering': ['-fecha_muestreo'],
                'unique_together': {('equipo', 'fecha_muestreo')},
            },
        ),
    ]
