# Generated by Django 5.2.6 on 2026-01-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_muestreoequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermografiaAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_muestreo', models.DateField(help_text='Fecha del análisis de termografía')),
                ('hora_muestreo', models.TimeField(blank=True, help_text='Hora del análisis (opcional)', null=True)),
                ('temperatura_promedio', models.FloatField(default=0, help_text='Temperatura promedio en °C')),
                ('temperatura_minima', models.FloatField(default=0, help_text='Temperatura mínima en °C')),
                ('temperatura_maxima', models.FloatField(default=0, help_text='Temperatura máxima en °C')),
                ('porcentaje_zona_buena', models.FloatField(default=0, help_text='Porcentaje de zona normal (%)')),
                ('porcentaje_zona_alerta', models.FloatField(default=0, help_text='Porcentaje de zona de alerta (%)')),
                ('porcentaje_zona_critica', models.FloatField(default=0, help_text='Porcentaje de zona crítica (%)')),
                ('imagen_termica', models.ImageField(blank=True, help_text='Fotografía térmica capturada', null=True, upload_to='termografias/analisis_historico/')),
                ('resultado', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='normal', help_text='Resultado del análisis', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del análisis', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(help_text='Activo analizado', on_delete=django.db.models.deletion.CASCADE, related_name='analisis_termografia_historico', to='core.activo')),
            ],
            options={
                'verbose_name': 'Análisis de Termografía',
                'verbose_name_plural': 'Análisis de Termografía',
                'ordering': ['-fecha_muestreo'],
                'indexes': [models.Index(fields=['-fecha_muestreo'], name='core_termog_fecha_m_be2210_idx'), models.Index(fields=['activo', '-fecha_muestreo'], name='core_termog_activo__f6f88e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VibracionesAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_muestreo', models.DateField(help_text='Fecha del análisis de vibraciones')),
                ('hora_muestreo', models.TimeField(blank=True, help_text='Hora del análisis (opcional)', null=True)),
                ('velocidad_rms', models.FloatField(default=0, help_text='Velocidad RMS en mm/s')),
                ('aceleracion', models.FloatField(default=0, help_text='Aceleración en g (gravedades)')),
                ('frecuencia_dominante', models.FloatField(blank=True, help_text='Frecuencia dominante en Hz', null=True)),
                ('desplazamiento', models.FloatField(blank=True, help_text='Desplazamiento en µm (micras)', null=True)),
                ('resultado', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='normal', help_text='Resultado del análisis', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del análisis', null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(help_text='Activo analizado', on_delete=django.db.models.deletion.CASCADE, related_name='analisis_vibraciones_historico', to='core.activo')),
            ],
            options={
                'verbose_name': 'Análisis de Vibraciones',
                'verbose_name_plural': 'Análisis de Vibraciones',
                'ordering': ['-fecha_muestreo'],
                'indexes': [models.Index(fields=['-fecha_muestreo'], name='core_vibrac_fecha_m_0f4f25_idx'), models.Index(fields=['activo', '-fecha_muestreo'], name='core_vibrac_activo__f66478_idx')],
            },
        ),
    ]
