# Generated by Django 6.0 on 2026-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_termografiaanalisis_vibracionesanalisis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibracionesanalisis',
            name='resultado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('observacion', 'Observación'), ('alarma', 'Alarma'), ('falla', 'Falla'), ('sin_medicion', 'Sin Medición')], default='sin_medicion', help_text='Resultado del análisis', max_length=20),
        ),
    ]
